WAD_group_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('movie/<slug:movie_name_slug>/', views.show_movie, name='show_movie'),
    path('add_movie/', views.add_movie, name='add_movie'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('HOMEPAGE/',views.HOMEPAGE, name='HOMEPAGE'),
]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

slug = models.SlugField(unique=True)

class Movie(models.Model):
    title = models.CharField(max_length=128, unique=True)
    releaseDate = models.CharField(max_length=128)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    
    class Meta:
        verbose_name_plural = 'Movies'
    
    def __str__(self):
        return self.title
        
class Page(models.Model):
    category = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Movie, UserProfile
from django.contrib.auth.models import User

class MovieForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the movie name.")
    releaseDate = forms.CharField(max_length=128, help_text="Please enter the movie release date.")
    # slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Movie
        fields = ('title',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('https://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Movie, Page
from rango.forms import PageForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm, MovieForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

def HOMEPAGE(request):
    print(request.method)
    print(request.user)
    movie_list = Movie.objects.order_by('title')

    context_dict = {}
    context_dict['movies'] = movie_list

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/HOMEPAGE.html', context=context_dict)
    
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(request.COOKIES.get('visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits

def about(request):
    print(request.method)
    print(request.user)
    context_dict = {}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)

def show_movie(request, movie_name_slug):
    context_dict = {}

    try:
        movie = Movie.objects.get(title=movie_name_slug)
        pages = Page.objects.filter(category=movie)

        context_dict['pages'] = pages
        context_dict['movie'] = movie

    except Movie.DoesNotExist:
        context_dict['pages'] = None
        context_dict['movie'] = None
    
    return render(request, 'rango/movie.html', context=context_dict)

@login_required
def add_movie(request):
    form = MovieForm()

    if request.method == 'POST':
        form = MovieForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/HOMEPAGE/')
        
        else:
            print(form.errors)

    return render(request, 'rango/add_movie.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Movie.objects.get(slug=category_name_slug)
    except Movie.DoesNotExist:
        category = None

    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))

        else:
            print(form.errors)

    context_dict = {'form': form, 'category':category}
    return render(request, 'rango/add_page.html', context=context_dict)

def signup(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            register = True

        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/signup.html', context = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:HOMEPAGE'))

            else:
                return HttpResponse("Your account is disabled")

        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:HOMEPAGE'))

templates/rango/HOMEPAGE.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	HOMEPAGE
{% endblock %}
		


{% block body_block %}

		<form id="form"> 
			<input type="search" id="query" name="q" placeholder="Search...">
			<button>Search</button>
		</form>


		<h3>Quick Search Options</h3>
    
		<form id="quicksearch"> 
			<button type="button" href="#az">Movies/TV shows A-Z</button>
			<button type="button" href="#new">New Movies/TV shows</button>
			<button type="button" href="#topm">Top movies of last year</button>
			<button type="button" href="#toptv">Top TV shows of last year</button>
			<button type="button" href="#worst">Worst Movies/TV shows</button>
		</form>
      
		<h3>Popular Movies</h3>

		<script>
			let slideIndex = 1;
			showSlides(slideIndex);

			// Next/previous controls
			function plusSlides(n) {
				showSlides(slideIndex += n);
			}

			// Thumbnail image controls
			function currentSlide(n) {
				showSlides(slideIndex = n);
			}

			function showSlides(n) {
				let i;
				let slides = document.getElementsByClassName("mySlides");
				let dots = document.getElementsByClassName("dot");
				if (n > slides.length) {slideIndex = 1}
				if (n < 1) {slideIndex = slides.length}
				for (i = 0; i < slides.length; i++) {
					slides[i].style.display = "none";
				}
				for (i = 0; i < dots.length; i++) {
					dots[i].className = dots[i].className.replace(" active", "");
				}
				slides[slideIndex-1].style.display = "block";
				dots[slideIndex-1].className += " active";
			}

		</script>
    
		<div>

		{%if movies %}
		<ul>
		{%for movie in movies %}
			<li>
				<a href='/rango/movie/{{ movie.slug }}/'>{{ movie.title }}</a>
			</li>
		{%endfor%}
		</ul>
		{%else%}
			<strong>There are no movies present.</strong>
		{%endif%}

		</div>
		<br>
      
		<!-- The dots/circles -->
		<div style="text-align:center">
			<span class="dot" onclick="currentSlide(1)"></span>
			<span class="dot" onclick="currentSlide(2)"></span>
			<span class="dot" onclick="currentSlide(3)"></span>
		</div>

		{% if user.is_authenticated %}
		<a href="{% url 'rango:add_movie' %}">Add Movie</a>
		{% endif %}


		<h3>Popular TV Shows</h3>
	
		<div class="slideshow-container">
			<!-- Full-width images with number and caption text -->
			<div class="mySlides fade">
				<div class="numbertext">1 / 3</div>
					<img src="{{ MEDIA_URL }}img4.jpg" style="width:100%">
				<div class="text">Breaking Bad</div>
			</div>
      
			<div class="mySlides fade">
				<div class="numbertext">2 / 3</div>
					<img src="{{ MEDIA_URL }}img5.jpg" style="width:100%">
				<div class="text">The Simpsons</div>
			</div>
		
			<div class="mySlides fade">
				<div class="numbertext">3 / 3</div>
					<img src="{{ MEDIA_URL }}img6.jpg" style="width:100%">
				<div class="text">Game of Thrones</div>
			</div>
      
			<!-- Next and previous buttons -->
			<a class="prev" onclick="plusSlides(-1)">&#10094;</a>
			<a class="next" onclick="plusSlides(1)">&#10095;</a>
		</div>
		<br>
=======
      <!-- <div class="slideshow-container">

        <!-- Full-width images with number and caption text -->
        <!-- <div class="mySlides fade">
          <div class="numbertext">1 / 3</div>
          <img src="{{ MEDIA_URL }}img4.jpg" style="width:100%">
          <div class="text">Breaking Bad</div>
        </div>
      
        <div class="mySlides fade">
          <div class="numbertext">2 / 3</div>
          <img src="{{ MEDIA_URL }}img5.jpg" style="width:100%">
          <div class="text">The Simpsons</div>
        </div>
      
        <div class="mySlides fade">
          <div class="numbertext">3 / 3</div>
          <img src="{{ MEDIA_URL }}img6.jpg" style="width:100%">
          <div class="text">Game of Thrones</div>
        </div> --> -->
>>>>>>> 74951a74d9ac02fc1f040305de405425dbf9f9fd
      
		<!-- The dots/circles -->
		<div style="text-align:center">
			<span class="dot" onclick="currentSlide(1)"></span>
			<span class="dot" onclick="currentSlide(2)"></span>
			<span class="dot" onclick="currentSlide(3)"></span>
		</div>

		<div class="footer">
			<p>footer text test</p>
		</div>      

{% endblock %}



templates/rango/add_movie.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Add a Movie
{% endblock %}

{% block body_block %}
    <h1>Add a Movie</h1>
    <div>
        <form id="movie_form" method="post" action="{% url 'rango:add_movie' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Movie" />
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<title>
			{% block title_block %}
				TVRatingSystem
			{% endblock %}
		</title>
		<link rel="stylesheet" href="WAD.css">
	</head>
	<body>
	
		<div class="topnav">
			<a>TV RATINGS</a>
			{% if user.is_authenticated %}
			Hi {{ user.username }}!
			<a href="{% url 'rango:logout' %}">Logout</a>
			{% else %}
			<a href="{% url 'rango:login' %}">Login</a>
			<a href="{% url 'rango:signup' %}">Sign Up</a>
			{% endif %}
			<a href="{% url 'rango:HOMEPAGE' %}">Home</a>
		</div>
	
		<div>
		{% block body_block %}
		{% endblock %}
		</div>

	</body>
</html>

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    
    Username: <input type="text" name="username" value="" size="50" /><br />
    Password: <input type="password" name="password" value="" size="50" /><br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/movie.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if movie %}
        {{ movie.name }}
    {% else %}
        Unknown Movie
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if movie %}
    <h1>{{ movie.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No ratings for current movie.</strong>
    {% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' movie.slug %}">Add Page</a> <br />
    {% endif %}
    {% else %}
    The specified movie does not exist.
    {% endif %}
{% endblock %}

templates/rango/myaccount.html
<!DOCTYPE html>

<html>

<head>

</head>

<body>
  
  <form id="form"> 
    <input type="search" id="query" name="q" placeholder="Search...">
    <button>Search</button>
  </form>

  <h3>Account Information</h3>

<form action="" method="post">

<div class="container">
<label for="uname"><b>Change Password</b></label>
<input type="text" placeholder="Enter New Password" name="password" required>

<label for="psw"><b>Confirm Password</b></label>
<input type="password" placeholder="Confirm Password" name="changepassword" required>

<button type="submit">Confirm</button>

<div class="container" style="background-color:#f1f1f1">
  <a href="userreviews.html">View Reviews</a>
  </div>

<div class="container" style="background-color:#f1f1f1">
<a href="warnings.html">View Warnings</a>
</div>

    
    
</body>

</html>

templates/rango/signup.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for TVRatingSystem</h1>
{% if user.is_authenticated %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:HOMEPAGE' %}">Return to the homepage</a><br />
{% else %}

<h3>Welcome! Enter your details to create an account to rate, comment on, or add Movies and TV shows!</h3>

<form id="user_form" method="post" action="{% url 'rango:signup' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/rango/userreviews.html
<!DOCTYPE html>

<html>

<head>

</head>

<body>
  
  <form id="form"> 
    <input type="search" id="query" name="q" placeholder="Search...">
    <button>Search</button>
  </form>

  <h3>Account Reviews</h3>

    <p>You have no reviews to view at this time.</p>
    
    <div class="container" style="background-color:#f1f1f1">
        <a href="myaccount.html">View Account Overview</a>
        </div>

</body>

</html>

templates/rango/warnings.html
<!DOCTYPE html>

<html>

<head>

</head>

<body>
  
  <form id="form"> 
    <input type="search" id="query" name="q" placeholder="Search...">
    <button>Search</button>
  </form>

  <h3>Account Warnings</h3>

    <p>You have no warnings to view at this time.</p>
    
    <div class="container" style="background-color:#f1f1f1">
        <a href="myaccount.html">View Account Overview</a>
        </div>
</body>

</html>